spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.66.62.160:3306/weather
    username: root
    password: weatherroot
weather:
  data:
    init: false
    years: 10
